services:
  - type: web
    name: chatroom-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5500

  - type: web
    name: chatroom-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_WS_URL
        value: wss://chatroom-backend.onrender.com/ws 